# TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

## NUMPY

In [3]:
#Numpy là thư viện kiểu list
#vì:
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI
#để sử dụng numpy thì : pip install numpy
import numpy as np

In [ ]:
#Thử tạo 1 list
python_list = [1,2,3]
#Chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

In [ ]:
#list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [ ]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

In [ ]:
#Chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

In [ ]:
#Accessing và indexing
x = np.array([1,2,3,4,5,6,7,8]) #x = np.array(range(1,9))

In [ ]:
#Lấy số 4
x[3]

In [ ]:
#Lấy nhiều hơn 1 phần tử 
#Công thức [start:and:step]
#Lấy 1 2 3
x[0:3]

In [ ]:
#Lấy từ 3 - 8 theo 3 cách
#C1
x[2:8]

In [ ]:
#C2
x[2:]

In [ ]:
#Lấy số 3 và số 5
x[2],x[4]

In [ ]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

In [ ]:
#Lấy số 2
np_list[0,1]

In [ ]:
#lấy số 6
np_list[2,1]

In [ ]:
#Lấy[3,4], [5,6]]
#C1
np_list[1:3]

In [ ]:
#C2
np_list[1:]

In [ ]:
#C3
np_list[1:,:]

In [ ]:
#C4
np_list[[1,2],:]

In [ ]:
#C5
np_list[-2:]

In [ ]:
#Lấy 1 3 5
np_list[:,0]

In [ ]:
#Lấy 1 và 5
#C1
np_list[[0,2],0]

In [ ]:
#C2
np_list[0::2,0]

In [ ]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list = np.array(x)
np_list

In [ ]:
#Lấy 2 6 10 14
np_list[:,1]

In [ ]:
#lấy 7 và 11
#C1
np_list[1:3,2]

In [ ]:
#C2
np_list[[1,2],2]

In [ ]:
#Lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

In [ ]:
#Lấy 16 15 14 13
#C1
np_list[3,::-1]

In [ ]:
#C2
np_list[-1,::-1]

In [ ]:
#BTVN thú vị
#Cho ma trận = [[99,99,99],]
#               [99,99,99],
#               [99,99,99]]

#Hãy tưởng tượng ô thứ 99 trống
#Giả sử 1 là x
#Giả sử 0 là 0

#Lấy đầu vào từ phía X và phí o luân phiên
#Nếu đầu vào từ phía X là (0,0)

#Ma trận sẽ trở thành
#[[x,99,99],
# [99,99,99],
# [99,99,99]]

#Nếu đầu vào từ phía o cũng là (0,0)
#Thông báo họ nhập lại
#Nếu không thì điền vào ma trận

#Thử thách: Nếu người đầu tiên có 3 phần tử liên tử liên tiếp thì dừng trò chơi.

In [ ]:
board = np.full((3, 3), 99)
def print_board():
    print(board)
    print()
def check_win(player):
    # kiểm tra hàng
    for i in range(3):
        if np.all(board[i, :] == player):
            return True

    # kiểm tra cột
    for i in range(3):
        if np.all(board[:, i] == player):
            return True

    # kiểm tra chéo
    if np.all(np.diag(board) == player):
        return True

    if np.all(np.diag(np.fliplr(board)) == player):
        return True

    return False
current_player = 1  

while True:
    print_board()

    if current_player == 1:
        print("Lượt của X")
    else:
        print("Lượt của O")

    row = int(input("Nhập dòng (0-2): "))
    col = int(input("Nhập cột (0-2): "))

    # kiểm tra ô trống
    if board[row, col] != 99:
        print("Ô này đã được đánh, nhập lại!")
        continue

    # điền vào ma trận
    board[row, col] = current_player

    # kiểm tra thắng
    if check_win(current_player):
        print_board()
        print("X thắng!" if current_player == 1 else "O thắng!")
        break

    # đổi lượt
    current_player = 0 if current_player == 1 else 1



In [1]:
#BTVN 2
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
#Lấy 4,5,6
#Lấy 2,5
#Lấy 3,4
#Lấy 9,6,3

In [4]:
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
np_list = np.array(y)
np_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#Lấy 4,5,6
np_list[1]

array([4, 5, 6])

In [6]:
#Lấy 2,5
np_list[[0,1],[1,1]]

array([2, 5])

In [7]:
#Lấy 3,4
np_list[[0,1],[2,0]]

array([3, 4])

In [8]:
#Lấy 9,6,3
np_list[::-1,2]

array([9, 6, 3])

In [ ]:
#BTVN 3
#Cho x = [1,2,3,4,5,6,7,8,9,10]

#1. Xuất ra các giá trị chẵn sử dụng if
#2. Xuất ra các giá trị chẵn sử dụng list comprehension

In [10]:
x = [1,2,3,4,5,6,7,8,9,10]
np_x = np.array(x)
np_x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#1. Xuất ra các giá trị chẵn sử dụng if
for i in x:
    if i % 2 == 0:
        print(i)

2
4
6
8
10


In [ ]:
#2. Xuất ra các giá trị chẵn sử dụng list comprehension
even = []
for i in x:
    if i % 2 == 0:
        even.append(i)
even = np.array(even)
print(even)

[ 2  4  6  8 10]


In [13]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
np_x % 2 == 0

In [ ]:
idx = [True, True, True, False, True, True, True, False, True, False]
np_x[idx]

In [ ]:
np_x

In [ ]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

In [ ]:
#BTVN 4
#Tạo mảng numpy có kích thước 150x5. Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình.
#Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là X và cột cuối cùng thành y
#Tách X thành X_train và X_test, trong đó Y_train chứa 70% dữ liệu
#Tạo 10 dữ liệu X_train không chồng chéo nhau

In [15]:
data = np.random.rand(150, 5)
data


array([[1.37748668e-01, 8.75624490e-01, 4.09393192e-02, 4.73588739e-01,
        7.41127652e-01],
       [6.00359350e-01, 7.16494762e-01, 3.36353265e-01, 9.67114093e-01,
        9.58286032e-01],
       [4.36325730e-01, 8.02999500e-01, 9.39956673e-01, 7.79681078e-02,
        8.19595681e-01],
       [5.97271288e-01, 9.12473587e-01, 1.84379712e-01, 9.71699782e-01,
        6.96608545e-01],
       [6.06780526e-01, 5.59355132e-01, 2.34664418e-01, 9.64942459e-01,
        4.48702587e-01],
       [6.41091892e-01, 1.55220040e-01, 7.47531229e-01, 4.67818242e-01,
        9.62467555e-02],
       [6.36667087e-01, 2.22973152e-03, 6.61728600e-01, 3.76250267e-01,
        5.07300354e-01],
       [7.42157888e-01, 9.20254598e-01, 1.31501656e-01, 8.29511647e-01,
        9.90008773e-01],
       [1.39976413e-01, 5.97298262e-02, 6.59303331e-02, 7.12601130e-02,
        8.29646420e-02],
       [9.97692548e-01, 9.63621125e-01, 9.11334909e-01, 3.03497843e-01,
        6.82688021e-01],
       [3.47744215e-01, 9.7622

In [16]:
X = data[:, :4]
y = data[:, 4]

In [17]:
n_train = int(0.7 * len(X))
n_train

105

In [18]:
X_train = X[:n_train]
X_train


array([[0.13774867, 0.87562449, 0.04093932, 0.47358874],
       [0.60035935, 0.71649476, 0.33635326, 0.96711409],
       [0.43632573, 0.8029995 , 0.93995667, 0.07796811],
       [0.59727129, 0.91247359, 0.18437971, 0.97169978],
       [0.60678053, 0.55935513, 0.23466442, 0.96494246],
       [0.64109189, 0.15522004, 0.74753123, 0.46781824],
       [0.63666709, 0.00222973, 0.6617286 , 0.37625027],
       [0.74215789, 0.9202546 , 0.13150166, 0.82951165],
       [0.13997641, 0.05972983, 0.06593033, 0.07126011],
       [0.99769255, 0.96362112, 0.91133491, 0.30349784],
       [0.34774422, 0.97622586, 0.63572212, 0.63888223],
       [0.35048422, 0.60577622, 0.1154474 , 0.00309517],
       [0.75507966, 0.01329141, 0.61809059, 0.72527657],
       [0.97942178, 0.33377084, 0.62484719, 0.53800094],
       [0.31606308, 0.26541635, 0.04219908, 0.1555373 ],
       [0.34468925, 0.61837386, 0.74322927, 0.31436671],
       [0.32435553, 0.52060887, 0.41306929, 0.26116769],
       [0.26968957, 0.1493059 ,

In [19]:
X_test  = X[n_train:]
X_test

array([[6.08544988e-01, 9.59127535e-01, 7.47878946e-01, 9.35874464e-01],
       [2.49676646e-01, 7.31344406e-01, 9.20816792e-01, 5.70570189e-01],
       [9.88880500e-01, 3.94368970e-02, 6.81615655e-01, 5.88718833e-01],
       [7.09208819e-01, 5.18193521e-01, 6.29769423e-01, 4.49761764e-01],
       [7.98386070e-01, 2.11134496e-01, 7.94736643e-01, 3.30720520e-01],
       [9.54273622e-01, 9.95600505e-01, 1.04592830e-01, 6.94347318e-01],
       [1.37044291e-01, 8.64271210e-01, 3.63454710e-01, 3.71845967e-01],
       [9.18573295e-01, 1.74023545e-01, 9.28291046e-01, 9.94571490e-01],
       [5.73204308e-01, 8.47825415e-01, 7.15442267e-01, 2.48148934e-01],
       [9.96194104e-02, 4.33377892e-01, 1.67273857e-01, 7.55738312e-01],
       [8.12539020e-01, 4.82879156e-01, 9.25381585e-01, 7.73528072e-01],
       [1.77049703e-01, 2.56384901e-01, 2.89448556e-01, 5.41971607e-01],
       [4.23128661e-01, 6.79369237e-01, 1.73144474e-01, 1.04517998e-01],
       [8.46776990e-01, 1.06501017e-01, 3.22020804e

In [20]:
y_train = y[:n_train]
y_train

array([0.74112765, 0.95828603, 0.81959568, 0.69660854, 0.44870259,
       0.09624676, 0.50730035, 0.99000877, 0.08296464, 0.68268802,
       0.43132692, 0.68491322, 0.97496657, 0.85639772, 0.59397797,
       0.83742198, 0.09405695, 0.27523657, 0.20362068, 0.95152239,
       0.931118  , 0.86806183, 0.2491759 , 0.08634521, 0.80187197,
       0.61340174, 0.95929459, 0.95273225, 0.20014278, 0.9881065 ,
       0.59230499, 0.25473556, 0.13964502, 0.82796389, 0.84522161,
       0.12789055, 0.72622547, 0.22568862, 0.19202924, 0.92719888,
       0.68053368, 0.8985739 , 0.4588216 , 0.78360089, 0.79975653,
       0.2091642 , 0.58555993, 0.97833522, 0.01657933, 0.39881986,
       0.58635614, 0.16818535, 0.02445122, 0.55009249, 0.62394624,
       0.51216327, 0.82010499, 0.26821047, 0.46994685, 0.99961778,
       0.63761291, 0.40958788, 0.24584277, 0.19498648, 0.39543507,
       0.10938927, 0.80961553, 0.86071915, 0.48874466, 0.42124923,
       0.81096442, 0.07861769, 0.56108793, 0.30410895, 0.22497

In [21]:
y_test  = y[n_train:]
y_test

array([0.43028932, 0.97494897, 0.65086075, 0.46633376, 0.21897614,
       0.50076236, 0.09020577, 0.82530484, 0.59074811, 0.07160988,
       0.35248012, 0.03350409, 0.6749797 , 0.8262194 , 0.30267053,
       0.55869235, 0.60639892, 0.38655328, 0.60914064, 0.65941218,
       0.56257229, 0.66642212, 0.23893763, 0.04615594, 0.65514668,
       0.78274053, 0.51909226, 0.99817073, 0.18364938, 0.81409726,
       0.70541829, 0.85066041, 0.61355543, 0.33832424, 0.73623181,
       0.61930503, 0.25983186, 0.98504329, 0.84441469, 0.16598866,
       0.22024684, 0.39894527, 0.65594629, 0.27480297, 0.65889923])

In [22]:
X_train_splits = np.array_split(X_train, 10)
X_train_splits

[array([[0.13774867, 0.87562449, 0.04093932, 0.47358874],
        [0.60035935, 0.71649476, 0.33635326, 0.96711409],
        [0.43632573, 0.8029995 , 0.93995667, 0.07796811],
        [0.59727129, 0.91247359, 0.18437971, 0.97169978],
        [0.60678053, 0.55935513, 0.23466442, 0.96494246],
        [0.64109189, 0.15522004, 0.74753123, 0.46781824],
        [0.63666709, 0.00222973, 0.6617286 , 0.37625027],
        [0.74215789, 0.9202546 , 0.13150166, 0.82951165],
        [0.13997641, 0.05972983, 0.06593033, 0.07126011],
        [0.99769255, 0.96362112, 0.91133491, 0.30349784],
        [0.34774422, 0.97622586, 0.63572212, 0.63888223]]),
 array([[0.35048422, 0.60577622, 0.1154474 , 0.00309517],
        [0.75507966, 0.01329141, 0.61809059, 0.72527657],
        [0.97942178, 0.33377084, 0.62484719, 0.53800094],
        [0.31606308, 0.26541635, 0.04219908, 0.1555373 ],
        [0.34468925, 0.61837386, 0.74322927, 0.31436671],
        [0.32435553, 0.52060887, 0.41306929, 0.26116769],
        [0.2